### ISSUE TITLE
RSpectra dependency

### ISSUE THREAD

**Issue by geneorama** [road2stat/imgsvd#4]
When I try loading `rARPACK` it says that `RSpectra` is required

So, perhaps you should add `RSpectra` as a dependency.

```
Attaching: rARPACK 
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
  there is no package called ‘RSpectra’
In addition: Warning message:
package ‘rARPACK’ was built under R version 3.2.4 
Error: package or namespace load failed for ‘rARPACK’
```

**Comment by yixuan** [comment]
Oh yeah, my apologies. I changed the dependence of `rARPACK`. It should be a quick fix though.

**Comment by geneorama** [comment]
Definitely no need to apologize I'm not even sure that it's worth mentioning since people can easily figure it out.  However, I know you wouldn't normally see that issue since you have everything installed, and it's an excuse to let you know that someone is paying attention to your work.

Although I was surprised that `RSpectra`  wasn't installed with `rARPACK`.  That probably means that `rARPACK` should be listed under DEPENDS or IMPORTS in the package DESCRIPTION file.  I can never remember which things should be labeled which way!

Thanks for sharing your code.
